# Generated by Django 4.2.20 on 2025-05-20 19:10

from django.db import migrations, models
import message_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        default=message_app.models.generate_message_id,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("sender_id", models.CharField(max_length=100)),
                ("receiver_id", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
