# Generated by Django 4.2.20 on 2025-05-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender_id", "receiver_id", "timestamp"],
                name="message_app_sender__510027_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_id"], name="message_app_message_a50638_idx"
            ),
        ),
    ]
